# TODO use Dev Container

name: Ci

on:
  push:
    branches:
    - main
    - feat/use-ci-devcontainer # TODO remove me!

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4

    - uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/yskszk63/wasinodot-devcontainer
        cacheFrom: ghcr.io/yskszk63/wasinodot-devcontainer
        push: always
        runCmd: cargo wasi build --release

    - run: |
        ls target/wasm32-wasi/release/wasinodot.wasm

    - name: Upload builds
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          target/wasm32-wasi/release/wasinodot.wasm

  release:
    if: ${{ false }}
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build

    - name: Remove latest nightly release
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        delete_release: true
        tag_name: nightly
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        prerelease: true
        files: |
          wasinodot.wasm
        tag_name: nightly
